In [49]:
import pandas as pd
from sodapy import Socrata

In [50]:
#api info at https://dev.socrata.com/foundry/data.cdc.gov/9mfq-cb36
#table info https://data.cdc.gov/Case-Surveillance/United-States-COVID-19-Cases-and-Deaths-by-State-o/9mfq-cb36

client = Socrata("data.cdc.gov",None)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [51]:
df = client.get("9mfq-cb36", limit=30000)

In [52]:
covid_df = pd.DataFrame.from_records(results)

In [53]:
covid_df= covid_df.sort_values(by=["submission_date", "state"])
covid_df

,submission_date,state,tot_cases,conf_cases,prob_cases,new_case,pnew_case,tot_death,new_death,pnew_death,created_at,consent_cases,consent_deaths,conf_death,prob_death
3725,2020-01-22T00:00:00.000,AL,0,0.0,0,0,0,0,0,0,2020-01-22T00:00:00.000,Agree,Agree,0.0,0
10873,2020-01-22T00:00:00.000,AR,0,NaN,NaN,0,NaN,0,0,NaN,2020-03-26T16:22:39.452,Not agree,Not agree,NaN,NaN
19422,2020-01-22T00:00:00.000,CA,0,0.0,0,0,0,0,0,0,2020-01-24T00:00:00.000,Agree,Not agree,NaN,NaN
13030,2020-01-22T00:00:00.000,CO,0,0.0,0,0,0,0,0,0,2020-01-22T00:00:00.000,Agree,Agree,0.0,0
17053,2020-01-22T00:00:00.000,DC,0,NaN,NaN,0,NaN,0,0,NaN,2020-03-26T16:22:39.452,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16387,2022-10-18T00:00:00.000,SC,1718563,1326050.0,392513,0.0,0,18527,0.0,0,2022-10-19T13:15:24.690,Agree,Not agree,NaN,NaN
10159,2022-10-18T00:00:00.000,SD,262837,NaN,NaN,0.0,0,3046,0.0,0,2022-10-19T13:15:24.690,N/A,Agree,3046.0,0
11654,2022-10-18T00:00:00.000,TN,2351660,1737249.0,614411,0.0,0,28017,0.0,0,2022-10-19T13:15:24.690,Agree,Agree,20128.0,7889
16137,2022-10-18T00:00:00.000,VA,2106527,1490236.0,616291,942.0,434,22057,16.0,2,2022-10-19T13:15:24.690,Agree,Agree,18326.0,3731
18065,2022-10-18T00:00:00.000,VI,23269,NaN,NaN,13.0,0,123,0.0,0,2022-10-19T13:15:24.690,NaN,NaN,NaN,NaN

In [63]:
#test= covid_df["new_death"].isnull().sum()
#test= pd.to_numeric(covid_df["new_death"], errors="coerce").notnull().all()
test= (covid_df["new_death"].dtype == "object").sum()
test

AttributeError: 'bool' object has no attribute 'sum'