In [52]:
import pandas as pd
from sodapy import Socrata

In [53]:
#api info at https://dev.socrata.com/foundry/data.cdc.gov/9mfq-cb36
#table info https://data.cdc.gov/Case-Surveillance/United-States-COVID-19-Cases-and-Deaths-by-State-o/9mfq-cb36

client = Socrata("data.cdc.gov",None)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [54]:
results = client.get("9mfq-cb36", limit=100000)

In [55]:
covid_df = pd.DataFrame.from_records(results)

In [56]:
covid_df= covid_df.sort_values(by=["submission_date", "state"])

In [60]:
#Update columns to intigers and correct date
covid_df["submission_date"]=pd.to_datetime(covid_df["submission_date"])
covid_df["tot_cases"]= covid_df['tot_cases'].apply(lambda x:int(float(x)))
covid_df["conf_cases"].fillna(0, inplace=True)
covid_df["conf_cases"]= covid_df['conf_cases'].apply(lambda x:int(float(x)))
covid_df["prob_cases"].fillna(0, inplace=True)
covid_df["prob_cases"]= covid_df['prob_cases'].apply(lambda x:int(float(x)))
covid_df["new_case"]= covid_df['new_case'].apply(lambda x:int(float(x)))
covid_df["pnew_case"].fillna(0, inplace=True)
covid_df["pnew_case"]= covid_df['pnew_case'].apply(lambda x:int(float(x)))
covid_df["new_death"]= covid_df['new_death'].apply(lambda x:int(float(x)))
covid_df["tot_death"]= covid_df["tot_death"].apply(lambda x:int(float(x)))
covid_df["pnew_death"].fillna(0, inplace=True)
covid_df["pnew_death"]= covid_df['pnew_case'].apply(lambda x:int(float(x)))
covid_df
#test= covid_df["new_death"].sum() + covid_df["pnew_death"].sum()
#test

,submission_date,state,tot_cases,conf_cases,prob_cases,new_case,pnew_case,tot_death,new_death,pnew_death,created_at,consent_cases,consent_deaths,conf_death,prob_death
55738,2020-01-22,AK,0,0,0,0,0,0,0,0,2020-03-26T16:22:39.452,N/A,N/A,NaN,NaN
3725,2020-01-22,AL,0,0,0,0,0,0,0,0,2020-01-22T00:00:00.000,Agree,Agree,0.0,0
10873,2020-01-22,AR,0,0,0,0,0,0,0,0,2020-03-26T16:22:39.452,Not agree,Not agree,NaN,NaN
59634,2020-01-22,AS,0,0,0,0,0,0,0,0,2020-03-26T16:22:39.452,NaN,NaN,NaN,NaN
44420,2020-01-22,AZ,0,0,0,0,0,0,0,0,2020-03-26T16:22:39.452,Agree,Agree,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30118,2022-10-18,VT,133845,0,0,184,39,700,0,39,2022-10-19T13:15:24.690,Not agree,Not agree,NaN,NaN
59911,2022-10-18,WA,1828918,0,0,12,0,14464,0,0,2022-10-19T13:15:24.690,N/A,N/A,NaN,NaN
37554,2022-10-18,WI,1884206,1658241,225965,1156,303,15374,8,303,2022-10-19T13:15:24.690,Agree,Agree,13588.0,1786
47586,2022-10-18,WV,605012,464040,140972,224,86,7479,3,86,2022-10-19T13:15:24.690,Agree,Not agree,NaN,NaN
31457,2022-10-18,WY,178032,139079,38953,397,134,1906,2,134,2022-10-19T13:15:24.690,Agree,Agree,1906.0,0